export interface ServiceDefinition {
  id: string;
  label: string;
  url: string;
  faviconUrl: string;
  category?: "video" | "music";
  isCustom?: boolean;
}

// DuckDuckGo favicon service returns images directly with no redirect.
const fav = (domain: string) =>
  `https://icons.duckduckgo.com/ip3/${domain}.ico`;

export const SERVICES: ServiceDefinition[] = [
  // ── Video streaming ───────────────────────────────────────────────────────
  {
    id: "apple-tv",
    label: "Apple TV+",
    url: "https://tv.apple.com",
    faviconUrl: fav("tv.apple.com"),
    category: "video",
  },
  {
    id: "bbc-iplayer",
    label: "BBC iPlayer",
    url: "https://www.bbc.co.uk/iplayer",
    faviconUrl: fav("bbc.co.uk"),
    category: "video",
  },
  {
    id: "binge",
    label: "Binge",
    url: "https://binge.com.au",
    faviconUrl: fav("binge.com.au"),
    category: "video",
  },
  {
    id: "britbox",
    label: "BritBox",
    url: "https://www.britbox.com",
    faviconUrl: fav("britbox.com"),
    category: "video",
  },
  {
    id: "canal-plus",
    label: "Canal+",
    url: "https://www.canalplus.com",
    faviconUrl: fav("canalplus.com"),
    category: "video",
  },
  {
    id: "crunchyroll",
    label: "Crunchyroll",
    url: "https://www.crunchyroll.com",
    faviconUrl: fav("crunchyroll.com"),
    category: "video",
  },
  {
    id: "dazn",
    label: "DAZN",
    url: "https://www.dazn.com",
    faviconUrl: fav("dazn.com"),
    category: "video",
  },
  {
    id: "disney-plus",
    label: "Disney+",
    url: "https://www.disneyplus.com",
    faviconUrl: fav("disneyplus.com"),
    category: "video",
  },
  {
    id: "hayu",
    label: "Hayu",
    url: "https://www.hayu.com",
    faviconUrl: fav("hayu.com"),
    category: "video",
  },
  {
    id: "hotstar",
    label: "Hotstar",
    url: "https://www.hotstar.com",
    faviconUrl: fav("hotstar.com"),
    category: "video",
  },
  {
    id: "hulu",
    label: "Hulu",
    url: "https://www.hulu.com",
    faviconUrl: fav("hulu.com"),
    category: "video",
  },
  {
    id: "itvx",
    label: "ITVX",
    url: "https://www.itv.com",
    faviconUrl: fav("itv.com"),
    category: "video",
  },
  {
    id: "max",
    label: "Max",
    url: "https://www.max.com",
    faviconUrl: fav("max.com"),
    category: "video",
  },
  {
    id: "mubi",
    label: "MUBI",
    url: "https://mubi.com",
    faviconUrl: fav("mubi.com"),
    category: "video",
  },
  {
    id: "netflix",
    label: "Netflix",
    url: "https://www.netflix.com",
    faviconUrl: fav("netflix.com"),
    category: "video",
  },
  {
    id: "now-tv",
    label: "NOW",
    url: "https://www.nowtv.com",
    faviconUrl: fav("nowtv.com"),
    category: "video",
  },
  {
    id: "paramount-plus",
    label: "Paramount+",
    url: "https://www.paramountplus.com",
    faviconUrl: fav("paramountplus.com"),
    category: "video",
  },
  {
    id: "peacock",
    label: "Peacock",
    url: "https://www.peacocktv.com",
    faviconUrl: fav("peacocktv.com"),
    category: "video",
  },
  {
    id: "prime-video",
    label: "Prime Video",
    url: "https://www.primevideo.com",
    faviconUrl: fav("primevideo.com"),
    category: "video",
  },
  {
    id: "skyshowtime",
    label: "SkyShowtime",
    url: "https://www.skyshowtime.com",
    faviconUrl: fav("skyshowtime.com"),
    category: "video",
  },
  {
    id: "stan",
    label: "Stan",
    url: "https://www.stan.com.au",
    faviconUrl: fav("stan.com.au"),
    category: "video",
  },
  {
    id: "twitch",
    label: "Twitch",
    url: "https://www.twitch.tv",
    faviconUrl: fav("twitch.tv"),
    category: "video",
  },
  {
    id: "viaplay",
    label: "Viaplay",
    url: "https://viaplay.com",
    faviconUrl: fav("viaplay.com"),
    category: "video",
  },
  {
    id: "viki",
    label: "Viki",
    url: "https://www.viki.com",
    faviconUrl: fav("viki.com"),
    category: "video",
  },
  {
    id: "youtube",
    label: "YouTube",
    url: "https://www.youtube.com",
    faviconUrl: fav("youtube.com"),
    category: "video",
  },
  // ── Music streaming ───────────────────────────────────────────────────────
  {
    id: "amazon-music",
    label: "Amazon Music",
    url: "https://music.amazon.com",
    faviconUrl: fav("music.amazon.com"),
    category: "music",
  },
  {
    id: "apple-music",
    label: "Apple Music",
    url: "https://music.apple.com",
    faviconUrl: fav("music.apple.com"),
    category: "music",
  },
  {
    id: "audiomack",
    label: "Audiomack",
    url: "https://audiomack.com",
    faviconUrl: fav("audiomack.com"),
    category: "music",
  },
  {
    id: "boomplay",
    label: "Boomplay",
    url: "https://www.boomplay.com",
    faviconUrl: fav("boomplay.com"),
    category: "music",
  },
  {
    id: "deezer",
    label: "Deezer",
    url: "https://www.deezer.com",
    faviconUrl: fav("deezer.com"),
    category: "music",
  },
  {
    id: "gaana",
    label: "Gaana",
    url: "https://gaana.com",
    faviconUrl: fav("gaana.com"),
    category: "music",
  },
  {
    id: "jiosaavn",
    label: "JioSaavn",
    url: "https://www.jiosaavn.com",
    faviconUrl: fav("jiosaavn.com"),
    category: "music",
  },
  {
    id: "napster",
    label: "Napster",
    url: "https://napster.com",
    faviconUrl: fav("napster.com"),
    category: "music",
  },
  {
    id: "pandora",
    label: "Pandora",
    url: "https://www.pandora.com",
    faviconUrl: fav("pandora.com"),
    category: "music",
  },
  {
    id: "qobuz",
    label: "Qobuz",
    url: "https://www.qobuz.com",
    faviconUrl: fav("qobuz.com"),
    category: "music",
  },
  {
    id: "soundcloud",
    label: "SoundCloud",
    url: "https://soundcloud.com",
    faviconUrl: fav("soundcloud.com"),
    category: "music",
  },
  {
    id: "spotify",
    label: "Spotify",
    url: "https://open.spotify.com",
    faviconUrl: fav("open.spotify.com"),
    category: "music",
  },
  {
    id: "tidal",
    label: "Tidal",
    url: "https://listen.tidal.com",
    faviconUrl: fav("listen.tidal.com"),
    category: "music",
  },
  {
    id: "youtube-music",
    label: "YouTube Music",
    url: "https://music.youtube.com",
    faviconUrl: fav("music.youtube.com"),
    category: "music",
  },
];
